### PR TITLE
[WFX-346] Add toggle to force light/dark mode in dynamic themes.

### LINKED ISSUE #2562: Can't select Dark Theme when using Lepton Theme on Linux
### What happened?

Using `waterfox-g4-bin-0.6-0`package from AUR on Arch.
### On Linux that doesn't work by any means that I know of.
I only get the Lepton white and can't switch to the dark variant, a thing that on Windows 10 works by nicely asking you which one you want to use just after installation. Is there any way to fix that and make the dark theme work on Linux also? 
I've also tried the official build from the waterfox website but no joy. Thanks

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by adamp01**
Resolve #2562

### CODE REVIEW

File: browser/components/preferences/main.js [hunk 1]
```diff
@@ -214,7 +214,7 @@ Preferences.addAll([
   // Media
   { id: "media.hardwaremediakeys.enabled", type: "bool" },
 
-  // Waterfox
```
Comment (MrAlex94) [inline browser/components/preferences/main.js]: Pls have this fixed in the previous PR, makes potential merging/squashing in the future difficult otherwise.

Comment (adamp01) [reply browser/components/preferences/main.js]: The previous PR doesn't touch this file?

**Review by MrAlex94 — APPROVED** [review]
